# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(db_index=True, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='State',
            field=models.CharField(db_index=True, max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='Street',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Street'),
        ),
    ]
