version: '2'
services:
   db1:
     image: postgres:9.4
     volumes:
       - ./pgdata1:/var/lib/postgresql/data/
   web1:
     build: micro1
     command: bash -c "sleep 10 && python manage.py runserver 0.0.0.0:8881  2>&1 | tee logs/web1.log"
     ports:
       - "8881:8881"
     volumes:
       - ./log1:/micro1/logs/
     depends_on:
       - db1
       - web2
   db2:
     image: postgres:9.4
     volumes:
       - ./pgdata2:/var/lib/postgresql/data/
   web2:
     build: micro2
     command: bash -c "sleep 10 && python manage.py runserver 0.0.0.0:8882 2>&1 | tee logs/web2.log"
     ports:
       - "8882:8882"
     volumes:
       - ./log2:/micro2/logs/
     depends_on:
       - db2
