# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('AddressId', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
