# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_auto_20161203_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='AddressId',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Address ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='FirstName',
            field=models.CharField(db_index=True, max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='LastName',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
